DROP TABLE IF EXISTS urlcheck;
DROP TABLE IF EXISTS urls;
CREATE TABLE urls (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  address                       VARCHAR(255),
  created_at                    TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_url PRIMARY KEY (id)
);

CREATE TABLE urlcheck (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  statusCode                    INTEGER NOT NULL,
  title                         VARCHAR(255),
  h1                            VARCHAR(255),
  description                   TEXT,
  urlId                         BIGINT NOT NULL,
  created_at                    TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_url_checks PRIMARY KEY (id)
);

CREATE INDEX ix_url_check_url_id ON urlcheck (urlId);
ALTER TABLE urlcheck ADD CONSTRAINT fk_url_checks_url_id FOREIGN KEY (urlId) REFERENCES urls (id) ON DELETE RESTRICT ON UPDATE RESTRICT;
